#version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: messi10
      POSTGRES_USER: bluk
      POSTGRES_DB: postgres-biblioteca
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
